### ISSUE TITLE
Error when switching to the next Facebook reel after activating the extension

### ISSUE THREAD

**Issue by DelteRT** [yacine-bens/facebook-video-controls-extension#1]
First of all, this extension is fantastic and very helpful! Thank you so much for creating it. It only has a minor issue that I'd like to report:

**Steps to reproduce the problem:**
1. Open a Facebook reel video that doesn't have controls.
2. Activate the extension by right-clicking on the video.
3. Use the controls provided by the extension to move the video.
4. Attempt to switch to the next reel.

**Expected behavior:**
The next reel should load and play without any issues.

**Actual behavior:**
Upon trying to switch to the next reel, almost always receive the error: "This page is currently unavailable. This may be due to a technical error that we were trying to fix. Please try refreshing this page."

**Frequency:**
The error occurs almost every time after switching one or a maximum of two reels following the use of the extension.

**Additional information:**
- Extension version: 0.0.1
- Chrome version: 124.0.6367.210 (Official Build) (64-bit)
- Operating system: Windows 10
- Browser language: Spanish

It would also be fantastic if there was an option to keep the extension always active by default, so I don't have to manually activate it each time I watch a reel.

**Comment by yacine-bens** [comment]
Hey! I'm glad you found the extension helpful.

Thank you for reporting the issue and for the detailed explanation, it really helps solving issues faster. I'll look into this as soon as get a chance to.

Keeping the extension active so that it always shows video controls is really interesting, this could be set as an option (on/off).

**Comment by yacine-bens** [comment]
I tested it on my end and I can confirm the issue. 

There's a hidden DIV element on top of the video element that blocks the user from interacting with video controls. It only allows to Play / Pause the video. I'm deleting this element after enabling video controls, but when switching to another reel, Facebook needs that element to show the next video and that's what's causing the issue.

Setting `style.display = 'none'` instead of deleting it seems to work. 

I'll update the extension and publish the new version. If you're installing it manually it should be available as soon as I push the changes, but if you're installing it through Chrome Web Store, the review process will take a while (usually a couple of hours).
